#!/usr/bin/env python3
"""Generate shim_vtables.h — per-VERSION MSVC vtables with i386-correct arity (#20).

Reads extract_vtables.py's JSON and emits, for every supported interface
version: a slot-exact stub table, a name->slot map, and a descriptor. Two
problems this solves, both of which bit us:

 1. i386 thiscall is CALLEE-cleanup. A stub that pops the wrong number of bytes
    corrupts the caller's stack. On x86_64 (caller-cleanup) arity is free, which
    is why #11's 0-arg stubs were safe and why that safety does NOT carry over.
    Proton's DEFINE_THISCALL_WRAPPER(<method>, <bytes>) is the authority; bytes
    INCLUDE `this`, so a stub takes (bytes - 4) / 4 extra dwords.

 2. Vtables are per-VERSION, not per-interface. SteamInput006 inserts
    SetInputActionManifestFilePath at slot 2 and shifts every later slot against
    SteamInput002 — Mars asks for 006, Among Us for 002. Serving one layout for
    both silently calls the wrong method (map trap 2). Wiring is therefore
    resolved BY NAME against the version's own table, never by literal index.

 3. The MSVC order is not the order the macOS dylib was compiled in. Inside a
    set of same-name overloads MSVC reverses the run, so a slot resolved here
    and sent across the seam would land on a SIBLING overload — GetStat(int32*)
    calling GetStat(float*) (#78). Each method therefore carries BOTH indices:
    `slot`, where it sits in the table the title calls through, and `native`,
    where the same method sits in the dylib's vtable. msvc_order.py owns that
    correspondence; everything here just writes it down.

Usage: gen_vtables.py <tables.json> <out.h>
"""
import json, sys
import msvc_order

def ident(v):  # version strings are already valid C identifiers
    return v

def main():
    src, out = sys.argv[1], sys.argv[2]
    data = json.load(open(src))
    tables = data['tables']
    if data['problems']:
        sys.exit('refusing to generate, extractor reported problems:\n  ' +
                 '\n  '.join(data['problems']))

    L = []
    w = L.append
    w('/* GENERATED by gen_vtables.py from Proton lsteamclient (proton_11.0).')
    w(' * DO NOT EDIT. Regenerate:  ./build.sh --regen-vtables')
    w(' * See extract_vtables.py for why these numbers and not the SDK headers. */')
    w('#pragma once')
    w('')
    w('/* bytes = the i386 thiscall stack size INCLUDING `this`, straight from')
    w(' * Proton\'s DEFINE_THISCALL_WRAPPER. Kept at runtime so wiring can tell')
    w(' * apart methods whose shape varies across an interface (see wire_getters). */')
    w('/* slot   = where the method sits in the MSVC table the TITLE calls through.')
    w(' * native = where the same method sits in the DYLIB\'s vtable, which is')
    w(' *          declaration order. They differ only inside a same-name overload')
    w(' *          set, which MSVC lays out reversed — and that difference is the')
    w(' *          whole reason both are kept. Sending `slot` across the seam for')
    w(' *          an overloaded method calls its sibling (#78). */')
    w('struct vt_method { const char *name; unsigned short slot; unsigned short native; unsigned short bytes; };')
    w('/* iface is the INTERFACE this version belongs to ("ISteamClient"), taken')
    w(' * from Proton\'s own tag. It is what lets wiring say "every version of')
    w(' * ISteamClient" instead of naming version strings one at a time — naming')
    w(' * them is how SteamClient021 ended up with a correct table whose slots')
    w(' * were all still stubs (#29). */')
    w('struct vt_desc {')
    w('    const char *version;')
    w('    const char *iface;')
    w('    const void **vtable;')
    w('    unsigned short nslots;')
    w('    const struct vt_method *methods;')
    w('};')
    w('')
    w('/* Defined by the PE half: logs "<version> slot N <name> (unmapped)". */')
    w('static unsigned int vt_unmapped(const char *version, int slot, const char *name);')
    w('')

    # Resolve the MSVC -> native correspondence up front, so a version whose
    # overload sets are not contiguous stops the build here rather than being
    # generated on a premise that has already failed.
    natives = {}
    for ver, t in tables.items():
        try:
            natives[ver] = msvc_order.native_slots(t['slots'])
        except msvc_order.OrderProblem as e:
            sys.exit('%s: %s' % (ver, e))

    nstub = 0
    for ver, t in tables.items():
        slots = t['slots']
        w('/* ---- %s (%d slots, %s) ---- */' % (ver, len(slots), t['source']))
        for s in slots:
            b = s['bytes']
            if b is None or (b - 4) % 4:
                sys.exit('%s slot %d (%s): bad stack_bytes %r' % (ver, s['slot'], s['name'], b))
            nargs = (b - 4) // 4
            args = ''.join(', unsigned int a%d' % i for i in range(nargs))
            w('static unsigned int THISCALL stub_%s_%d(void *self%s)'
              % (ident(ver), s['slot'], args))
            w('{ (void)self; return vt_unmapped("%s", %d, "%s"); }'
              % (ver, s['slot'], s['name']))
            nstub += 1
        w('static const void *vt_%s[%d];' % (ident(ver), len(slots)))
        w('static const struct vt_method meth_%s[] = {' % ident(ver))
        for s in slots:
            w('    { "%s", %d, %d, %d },'
              % (s['name'], s['slot'], natives[ver][s['slot']], s['bytes']))
        w('    { 0, 0, 0, 0 }')
        w('};')
        w('')

    w('static void vt_fill_stubs(void)')
    w('{')
    for ver, t in tables.items():
        for s in t['slots']:
            w('    vt_%s[%d] = (const void *)stub_%s_%d;'
              % (ident(ver), s['slot'], ident(ver), s['slot']))
    w('}')
    w('')
    w('static const struct vt_desc g_vtdescs[] = {')
    for ver, t in tables.items():
        # winISteamClient_SteamClient021 -> ISteamClient
        iface = t['tag'].split('_', 1)[0]
        iface = iface[3:] if iface.startswith('win') else iface
        w('    { "%s", "%s", vt_%s, %d, meth_%s },'
          % (ver, iface, ident(ver), len(t['slots']), ident(ver)))
    w('    { 0, 0, 0, 0 }')
    w('};')
    open(out, 'w').write('\n'.join(L) + '\n')
    nrev = sum(1 for ver in tables for s in tables[ver]['slots']
               if natives[ver][s['slot']] != s['slot'])
    print('%s: %d versions, %d slots/stubs, %d slots reversed by MSVC overload order'
          % (out, len(tables), nstub, nrev))

main()
