#!/usr/bin/env python3
"""Generate a shadow DLL's export surface from a reference PE (ADR 0014).

Valve's signed Steam client DLL imports from two non-system libraries of its own.
We
replace them so that OUR code runs during its load — and for the loader to bind
it, every name it imports must exist as an export on ours.

The list is taken from the reference library's EXPORT table, not from
steamclient64's import table, deliberately: exports are a superset of what any
one client build imports, so a Steam client update that starts importing one
more name still binds. A build that removed exports would not, and that is what
check() in the caller is for.

The stubs are never called. Once the trampolines are installed and
steamclient64's entry point is neutered, none of Valve's code in that process
runs at all — these exist only to satisfy the loader.

    gen_shadow.py <reference.dll> <out.c> <out.def> <symbol-prefix>
"""
import struct
import sys


def exports(path):
    """Exported names of a PE, in file order. Enough of a PE reader for this
    one job: the export directory's name table, mapped back through the section
    headers. Anything malformed is fatal — a partial list would produce a DLL
    that fails to bind with no explanation."""
    d = open(path, "rb").read()
    if d[:2] != b"MZ":
        sys.exit("%s: not a PE" % path)
    e = struct.unpack_from("<I", d, 0x3C)[0]
    if d[e:e + 4] != b"PE\0\0":
        sys.exit("%s: no PE header" % path)
    nsec = struct.unpack_from("<H", d, e + 6)[0]
    szopt = struct.unpack_from("<H", d, e + 20)[0]
    magic = struct.unpack_from("<H", d, e + 24)[0]
    secs = []
    for i in range(nsec):
        o = e + 24 + szopt + i * 40
        va, vsz = struct.unpack_from("<II", d, o + 12)[0], struct.unpack_from("<I", d, o + 8)[0]
        raw, rsz = struct.unpack_from("<II", d, o + 20)[0], struct.unpack_from("<I", d, o + 16)[0]
        secs.append((va, max(vsz, rsz), raw))

    def off(rva):
        for va, sz, raw in secs:
            if va <= rva < va + sz:
                return raw + (rva - va)
        sys.exit("%s: RVA %#x maps to no section" % (path, rva))

    dd = e + 24 + (0x70 if magic == 0x20B else 0x60)
    exp = struct.unpack_from("<I", d, dd)[0]
    if not exp:
        sys.exit("%s: no export directory" % path)
    ed = off(exp)
    n = struct.unpack_from("<I", d, ed + 24)[0]
    names = struct.unpack_from("<I", d, ed + 32)[0]
    out = []
    for i in range(n):
        rva = struct.unpack_from("<I", d, off(names) + i * 4)[0]
        o = off(rva)
        out.append(d[o:d.index(b"\0", o)].decode("ascii"))
    return out


def main():
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    ref, out_c, out_def, prefix = sys.argv[1:]
    names = exports(ref)
    if not names:
        sys.exit("%s: no exports" % ref)

    with open(out_c, "w") as f:
        f.write("/* GENERATED by gen_shadow.py from %s. DO NOT EDIT.\n"
                " *\n"
                " * %d no-op stubs, one per export of the reference library. They exist so\n"
                " * the loader can bind the signed client DLL; none is ever called, because\n"
                " * entry point is neutered before any of its code runs (ADR 0014). */\n"
                % (ref.rsplit("/", 1)[-1], len(names)))
        for i in range(len(names)):
            f.write("void %s%d(void) { }\n" % (prefix, i))

    with open(out_def, "w") as f:
        f.write("EXPORTS\n")
        for i, n in enumerate(names):
            f.write("%s = %s%d\n" % (n, prefix, i))
    print("drm: %s -> %d stub exports" % (out_def.rsplit("/", 1)[-1], len(names)))


if __name__ == "__main__":
    main()
